"""
ASCII Weather Plugin for AutoDevCore
A simple plugin that generates ASCII weather art
"""

import random
from datetime import datetime


def run(input_text: str) -> str:
    """
    Run the ASCII weather plugin.
    
    Args:
        input_text: Input text (unused in this plugin)
        
    Returns:
        ASCII weather art
    """
    weather_conditions = [
        "☀️ Sunny",
        "🌧️ Rainy", 
        "⛅ Partly Cloudy",
        "❄️ Snowy",
        "🌪️ Stormy",
        "🌈 Rainbow"
    ]
    
    weather = random.choice(weather_conditions)
    current_time = datetime.now().strftime("%H:%M")
    
    ascii_art = f"""
    ╔══════════════════════════════════════════════════════════════╗
    ║                    AutoDevCore Weather                       ║
    ║                                                              ║
    ║  Current Time: {current_time}                                    ║
    ║  Weather: {weather:<45} ║
    ║                                                              ║
    ║  {_get_weather_ascii(weather)}  ║
    ║                                                              ║
    ║  Plugin Status: ✅ Active                                     ║
    ║  Generated by: ASCII Weather Plugin                          ║
    ╚══════════════════════════════════════════════════════════════╝
    """
    
    return ascii_art


def _get_weather_ascii(weather: str) -> str:
    """Get ASCII art for the weather condition."""
    if "Sunny" in weather:
        return """
        ☀️
        """
    elif "Rainy" in weather:
        return """
        🌧️
        """
    elif "Cloudy" in weather:
        return """
        ⛅
        """
    elif "Snowy" in weather:
        return """
        ❄️
        """
    elif "Stormy" in weather:
        return """
        🌪️
        """
    elif "Rainbow" in weather:
        return """
        🌈
        """
    else:
        return """
        🌤️
        """
